services:
  # Backend API (Must be type: web)
  - type: web
    name: youtube-downloader-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DOWNLOAD_FOLDER
        value: /tmp/downloads

  # Frontend Static Site
  - type: static
    name: youtube-downloader-frontend
    env: static
    # No plan: free needed for static sites
    buildCommand: "" # Leave empty if you have no build step
    staticPublishPath: ./frontend 
